"""Initial migration

Revision ID: 7783c3d5f7dc
Revises: 7632e0c1a651
Create Date: 2025-04-03 04:36:47.935391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7783c3d5f7dc'
down_revision: Union[str, None] = '7632e0c1a651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
